Требования:
  Таск-трекер:
    - Авторизация через UberPopug Inc
    - Отдельный дашборд для всех ролей
    - Задача - описание, статус (да/нет), назначенный попуг. Новые задачи - все роли. # + цена
    - Кнопка реассайна задач - менеджеры и администраторы. (на каждого сотрудника - любое количество задач)
    - Сотрудник - должен видеть список своих задач + кнопка выполнить.

  Аккаунтинг:
    - Авторизация через UberPopug Inc
    - Отдельный дашборд
      - Для администраторов и бухгалтеров - общая стата по заработанным деньгам (кол-во за сегодня и по дням)
        (sum(completed task amount) + sum(assigned task fee)) * -1 # ?
      - Для рабочего - аудит лог + текущий баланс
    - Для рабочих - счет, сколько за сегодня получил денег + лог с подробным описанием задач
    - Цена задачи - в момент создания. Ассайн - списать rand(-10..-20)$, выполнение - начислить rand(20..40)$.
      Отрицательный баланс - на следующий день.
    - В конце дня - сколько получил сотрудник за день и отправить на мыло сумму выплаты # на мыло кому? Сотруднику или руководству?
    - После выплаты баланса (в конце дня) - баланс обнуляется, в аудитлоге операций аккаунтинга - отобразить что
      выплачена сумма # чей баланс? Попуга?
      # аудитлоге ВСЕХ операций аккаунтинга - это что?
    - Информация по дням

  Аналитика:
    - Отдельный дашборд для админов
    - Сколько заработал топ-менеджмент сегодня и сколько попугов ушло в минус
    - Показывать самую дорогую задачу за день, неделю, месяц. Самой дорогой задачей является задача с наивысшей ценой из
      списка всех закрытых задач за определенный период времени.

Таблицы:
  - попуги (все роли?)
  - задачи
  - заработанное менеджментом за день # обновляется только сегодняшний день по реассайну
  - счет для рабочего (по дням? может и не по дня, а общий, тогда это поле на попуге) # обновляется по реассайну
  - аудит лог для счета рабочего (?) # обновляется по реассайну и выполнению задачи

События:
  - попуг решает задачу
    -> меняется баланс попуга
    -> записывается лог в аудитлог попуга
    -> меняется общий заработок топов
  - нажата кнопка реассайна
    -> меняются записи задач - ассайнер
    -> меняется баланс попуга
    -> записывается лог в аудитлог попуга
    -> меняется общий заработок топов
  - заканчивается день
    -> меняются балансы попугов (положительные)
    -> выплаты попугам записываются в аудитлог
    -> выплаты попугам отправляются им на мыло
- Сообщение с ассайном новой задачи для попуга хотелось бы видеть синхронным, как и весь конец дня. Остальное асинхронно.

Дополнительно:
- конец дня можно отправлять в аккаунтинг и нотифаер. Как генерится? Кроной в таск-трекере?

Не понятно:
- Сколько баз для разных сервисов? Нужны ли разные? Зачем делят на сервисы? (деплой)
- Если по бизнес-цепочкам - тогда надо сервис для каждой роли. И дублировать информацию между базами (если их несколько).